### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by malteos** [ncg-task/training-data#1]
Hi all,

not all info-unit files are valid JSONs.

See https://raw.githubusercontent.com/ncg-task/training-data/master/text_generation/1/info-units/results.json

> SyntaxError: JSON.parse: bad control character in string literal at line 12 column 64 of the JSON data

Best regards
Malte

**Comment by ncg-task** [comment]
Hi Malte,

Do you find it is now resolved? We made a few fixes in the past weeks, but in all likelihood may have missed something. So if you still find the errors could you please share the file names?

Thank you.

**Comment by malteos** [comment]
Sadly no. Parsing with Python's `json.loads` still throws an error.

For [this one](https://raw.githubusercontent.com/ncg-task/training-data/master/text_generation/1/info-units/results.json), it is:

```
JSONDecodeError: Invalid control character at: line 12 column 64 (char 320)
```

**Comment by ncg-task** [comment]
Okay we'll be happy to make the fix. Could you share a list of the files where this error shows up? Thanks!

**Comment by ncg-task** [comment]
I am closing this issue because this dataset has been downloaded by other users and they seem to have been able to parse the data quite fine. I assume then it is the JSON parser library issue.
